# Site settings
title: Chakram
email: danielallenreid@gmail.com
description:
 "Chakram is an API testing framework designed to perform tests on JSON REST endpoints. The library offers a BDD testing style and fully exploits javascript promises"
baseurl: "/chakram" # the subpath of your site, e.g. /blog/
url: "http://dareid.github.io" # the base hostname & protocol for your site
github_username:  dareid/chakram
twitter_username: danielallenreid
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap